# Site settings
title: Apivich Hemachandra
general_email: apivich.hem at gmail dot com

description: > # this means to ignore newlines until "baseurl:"
  A website where I post things about me and my thoughts.

  Feel free to hang out here for a while.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://thecheesynachos.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: thecheesynachos
# linkedin_username: linkedin_username
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title

# plugins:
#   - jekyll-last-modified-at
#
# # Optional. The default date format, used if none is specified in the tag.
# last-modified-at:
#     date-format: '%d %B %Y'
